### ISSUE TITLE
Replace main branch with master branch

### ISSUE THREAD

**Issue by alexpartsch** [DDS-GmbH/jocument#17]
For some unknown reason we switched from master to main branch for the repositories default branch when migrating to Gitlab. To keep consistent with Gits branching strategy we want to reverse this:

1. Push main -> master
2. Make master the repos default branch
3. stale main branch

**Comment by AntonOellerer** [comment]
I created the master branch and switched the PRs to it, but I can not make it the default branch since I do not have the rights
