### ISSUE TITLE
Enable static code checking

### ISSUE THREAD

**Issue by AntonOellerer** [DDS-GmbH/jocument#6]
Currently, the checking of the code via checkstyle, sonarqube and owasp is disabled.
It should be enabled and the sources should be brought to compliance
* [x] Checkstyle (#14)
* [ ] Sonarqube (#26)
* [x] owasp (#13, #21)

**Comment by alexpartsch** [comment]
Integrate those into our GitHub actions workflows. It should be run by every commit into every branch.

**Comment by AntonOellerer** [comment]
Sonarqube does not support java 15 with pattern matching instanceof yet (https://jira.sonarsource.com/browse/SONARJAVA-3505)
